import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import "./globals.css";

const Exo2 = Exo_2({
  variable: "--font-exo2-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Exo2.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
